#!/usr/local/bin/perl

my $String = shift;
my $File = shift || die "$0 <grep string || defect number> <clearcase filename>\n";
my $Debug = shift;
my $DefectSearch = ($String =~ /^\d+$/);
my $s = "-s" unless $DefectSearch;

#Convert linked file
($File) = `ls -la $File` =~ /^l.* -> (.*)$/ if -l $File;

# Search through Clearcase history for this file
open(CTLSH, "cleartool lsh $s $File |") || die;
while(my $fver= <CTLSH>) {
	chomp($fver);
	if ($DefectSearch) {
		if ($fver =~ /DEFECT_ID:|Defect Id:/ && ($Cver!~ /@@\/main\/\d+$/)) {
			my @d = split(/;/,$fver);
			next if (scalar @d > 4); # Ignore merges
			if ($fver =~ /$String/) {
				print $Fullcreate . " : " . $fver . "\n";
				push(@deltas, $Cver);
			}
			print $fver . "\n" if $Debug;
		} elsif ($fver =~/create version/) {
			my @s = split(/\"/,$fver);
			# --02-04T15:03  jprewitt   create version "/vobs/projects/springboard/fabos/src/sys/route/new/rte_ctrlr.c@@/main/v6.4.0_pit_a/15"
			$Cver = $s[1];
			$Fullcreate = $fver;
			print "($Cver) from $fver\n" if $Debug;
		}
		next;
	}

	# String search
	next unless $fver =~/\/\d+$/;
	my ($branch,$rev) = get_branch_and_version($fver);
	my $grepstr = "grep -c \"$String\" $fver";
	my $out = `$grepstr`;
	chomp($out);
	if ($Branch{$branch} && $out == 0) {
		print "$grepstr: " . $out . "\n" if $Debug;
		print "vimdiff -R $fver $Branch{$branch}\n";
		push(@deltas, $Branch{$branch});
	}
	$Branch{$branch} = ($out) ? $fver : 0;
	print "$grepstr: " . $out . "\n" if $Debug;
}
close(CTLSH);

print "These branches always had the change:\n" if scalar keys %Branch;
foreach $b (keys %Branch) {
	print $Branch{$b} . "\n" if $Branch{$b};
}

do {
	$first_change = pop(@deltas);
} while (@deltas && $first_change =~ /\/main\/\d+$/g);

print `cleartool describe $first_change` if $first_change;






################################################################################
sub get_branch_and_version() {
	my $full = shift;
	my ($fb,$vs) = split(/@@/,$full,2);
	my @s = split(/\//,$vs);
	my $revnum = pop(@s);
	my $branch = join('/',@s);;
	return ($branch,$revnum);
}

