#!/usr/bin/perl

use strict;

if ($#ARGV > 0)
{
	print "Usage: setview [username]\n;";
	exit 0;
}


my $CLEARTOOL=`which cleartool`;
chomp($CLEARTOOL);

if ( $? !=0 )
{
	print "setview: cleartool not found in path. Exiting.\n";
	exit 0;
}
 
my $name;

if ($ARGV[0])
{
	$name=$ARGV[0];
}
else
{
	$name=getlogin;
}

print "Searching for views with: " . $name . "\n";
my @views=`$CLEARTOOL lsview -s "$name"`;

my $selection=1;
my @choices;
my $choice=1;
my $viewname;
my $viewpath;

foreach (@views)
{
	chomp;
	print $choice . ") " . $_ . "\n";
	$choices[$choice++]=$_;
}

if (scalar @views > 1) {
	while ($selection ne "q" && $choices[$selection] eq "") 
	{
		if ($selection != -1)
		{
			print "$selection is not a valid selection. (q to quit)\n";
		}
		
		print "Choice:";
		$selection=<STDIN>;
		chomp $selection;
	}
}

if ($selection ne "q")
{
	print "Setting view($selection):$choices[$selection]\n";
	exec("$CLEARTOOL setview $choices[$selection]"); 
}

