#!/usr/local/bin/perl 

while (my $line = <>) {
    push(@all,$line);   
}

$line = join(' ',@all);

$tag = '';
$on = 1;
foreach my $c (split(//,$line)) {
   $tag .= $c if ($on eq 0);
   $on = 0 if ($c eq "<");
   print "\n" if $tag =~ /\/Text\>/;
   print $c if $on;
   $on = 1 if ($c eq ">");
   $tag = '' if $on;
}
